-- ===================================================================
-- Palma Travel — contenido de ejemplo
-- -------------------------------------------------------------------
-- Carga los 6 paquetes de ejemplo, la propuesta de ejemplo y la
-- configuración inicial del sitio.
--
-- CÓMO USARLO
--   1. Entrá a tu proyecto en supabase.com
--   2. SQL Editor → New query
--   3. Pegá TODO este archivo y apretá Run
--
-- Correlo DESPUÉS de supabase/setup-completo.sql.
-- Se puede correr las veces que haga falta: actualiza en vez de duplicar.
--
-- Este archivo se genera solo desde /content/seed. No lo edites a mano:
-- una vez que el equipo empiece a cargar paquetes desde el panel, este
-- archivo deja de hacer falta.
-- ===================================================================


-- -------------------------------------------------------------------
-- PAQUETES (6)
-- -------------------------------------------------------------------

-- Bariloche con nieve: Cerro Catedral y Circuito Chico
insert into public.paquetes (
  slug,
  titulo,
  destino,
  pais,
  region,
  tipo_viaje,
  ideal_para,
  ritmo,
  duracion_dias,
  duracion_noches,
  fechas_salida,
  salida_grupal,
  coordinadores,
  precio_desde,
  moneda,
  base_precio,
  vigencia_precio,
  incluye_vuelo,
  incluye,
  no_incluye,
  itinerario,
  alojamiento,
  highlights,
  imagen_portada,
  galeria,
  documentacion,
  bases_y_condiciones,
  faq,
  tags,
  es_ejemplo,
  estado,
  destacado,
  ultimos_lugares,
  actualizado_por_nombre
) values (
  'bariloche-nieve-familia',
  'Bariloche con nieve: Cerro Catedral y Circuito Chico',
  'San Carlos de Bariloche',
  'Argentina',
  'sudamerica',
  ARRAY['nieve', 'naturaleza', 'aventura']::text[],
  ARRAY['familia', 'amigos', 'pareja']::text[],
  'moderado',
  7,
  6,
  '["2027-07-10","2027-07-17","2027-07-24"]'::jsonb,
  false,
  '{}'::text[],
  1290,
  'USD',
  'por persona en base doble',
  '2027-04-30',
  true,
  '["Pasaje aéreo Asunción – Bariloche – Asunción vía Buenos Aires, con equipaje de 23 kg","6 noches de alojamiento en el centro de Bariloche con desayuno","Traslados aeropuerto – hotel – aeropuerto","Excursión de día completo al Circuito Chico con guía","Traslado ida y vuelta al Cerro Catedral en dos jornadas","Asistencia al viajero con cobertura de deportes de nieve","Impuestos aéreos y tasas de embarque"]'::jsonb,
  '["Pase de esquí y alquiler de equipo en el Cerro Catedral","Clases de esquí o snowboard","Almuerzos y cenas","Excursión al Cerro Tronador y a Villa La Angostura (opcionales)","Gastos personales"]'::jsonb,
  '[{"dia":1,"titulo":"Asunción – Bariloche","descripcion":"Salida desde Asunción con conexión en Buenos Aires. Llegada a Bariloche, traslado al hotel y resto del día libre para caminar por el Centro Cívico y comprar chocolate."},{"dia":2,"titulo":"Circuito Chico","descripcion":"Excursión de día completo bordeando el lago Nahuel Huapi: Playa Bonita, isla Huemul, Punto Panorámico, Bahía López y el hotel Llao Llao. Subida opcional al Cerro Campanario."},{"dia":3,"titulo":"Cerro Catedral","descripcion":"Traslado al centro de esquí más grande de Sudamérica. Día completo en la nieve: pistas para todos los niveles, escuela de esquí y snowboard, y trineos para los más chicos."},{"dia":4,"titulo":"Día libre","descripcion":"Día libre en Bariloche. Buen momento para la excursión opcional a Villa La Angostura y el Bosque de Arrayanes, o para una tarde de cervecería artesanal."},{"dia":5,"titulo":"Segunda jornada en Cerro Catedral","descripcion":"Otra vez a la nieve, ya con el cerro conocido. Almuerzo en alguno de los refugios de altura, con vista a todo el valle."},{"dia":6,"titulo":"Día libre / Cerro Tronador (opcional)","descripcion":"Día libre. Recomendamos la excursión opcional al Cerro Tronador y el Ventisquero Negro, un día entero de montaña y glaciar."},{"dia":7,"titulo":"Bariloche – Asunción","descripcion":"Desayuno, tiempo libre según el horario del vuelo y traslado al aeropuerto para el regreso."}]'::jsonb,
  '[{"nombre":"Hotel Nevada","categoria":"4 estrellas","noches":6,"ciudad":"San Carlos de Bariloche"}]'::jsonb,
  '["Dos jornadas completas en el Cerro Catedral incluidas","Hotel en pleno centro, a pasos del Centro Cívico y las chocolaterías","Circuito Chico con guía, la excursión clásica de Bariloche","Pensado para que los chicos conozcan la nieve","Asistencia al viajero con cobertura de deportes de nieve incluida"]'::jsonb,
  '{"src":"/muestra/bariloche-portada.svg","alt":"Ilustración de picos nevados recortados contra un cielo gris claro"}'::jsonb,
  '[{"src":"/muestra/bariloche-1.svg","alt":"Ilustración de una cadena montañosa cubierta de nieve"},{"src":"/muestra/bariloche-2.svg","alt":"Ilustración de montañas verdes con un lago al pie"},{"src":"/muestra/bariloche-3.svg","alt":"Ilustración de un valle de montaña bajo el sol"}]'::jsonb,
  '[{"titulo":"Documento de identidad","detalle":"Los paraguayos pueden entrar a Argentina con la cédula de identidad vigente o con el pasaporte."},{"titulo":"Menores de edad","detalle":"Los menores que viajan sin ambos padres necesitan autorización de viaje. Te explicamos cómo tramitarla."},{"titulo":"Visa","detalle":"No se necesita visa para ciudadanos paraguayos."},{"titulo":"Vacunas","detalle":"No se exigen vacunas."}]'::jsonb,
  'Precios expresados en dólares americanos por persona en base doble, sujetos a disponibilidad y a confirmación al momento de la reserva. La temporada de nieve depende de las condiciones climáticas: Palma Travel no garantiza la apertura de pistas ni la cantidad de nieve del Cerro Catedral, ya que dependen del centro de esquí. El pase de esquí y el alquiler de equipo no están incluidos y se abonan en destino. Las tarifas aéreas pueden variar hasta la emisión de los pasajes. La reserva se confirma con una seña del 30% y el saldo debe abonarse 30 días antes de la salida. Cancelaciones con más de 45 días de anticipación: se retiene el 15%. Entre 45 y 21 días: se retiene el 50%. Con menos de 21 días o no presentación: sin reintegro. Los servicios no utilizados no son reembolsables. Palma Travel actúa como intermediario entre el pasajero y los prestadores de servicios, por lo que no se responsabiliza por hechos ajenos a su control. Es responsabilidad del pasajero contar con la documentación exigida por el país de destino.',
  '[{"pregunta":"¿Cuánto sale el pase de esquí?","respuesta":"Varía según la temporada y la cantidad de días. En julio, un pase diario de adulto ronda los 70 a 90 dólares y el alquiler de equipo completo entre 25 y 40 dólares por día. Te pasamos los valores actualizados al reservar."},{"pregunta":"¿Sirve si nunca esquié?","respuesta":"Sí. El Cerro Catedral tiene sector de principiantes y escuela con clases en español. Mucha gente del paquete esquía por primera vez."},{"pregunta":"¿Qué ropa hay que llevar?","respuesta":"Campera y pantalón impermeables, guantes, gorro, cuello y lentes de sol. Te mandamos una lista completa cuando confirmás. La ropa técnica también se puede alquilar en Bariloche."},{"pregunta":"¿Por qué dice próximamente?","respuesta":"Estamos cerrando las tarifas de la temporada de invierno. Dejanos tu contacto y te avisamos apenas abre la venta."}]'::jsonb,
  ARRAY['argentina', 'nieve', 'bariloche', 'esqui', 'invierno', 'familia', 'patagonia']::text[],
  true,
  'proximamente',
  false,
  false,
  'Carga inicial'
)
on conflict (slug) do update set
  titulo = excluded.titulo,
  destino = excluded.destino,
  pais = excluded.pais,
  region = excluded.region,
  tipo_viaje = excluded.tipo_viaje,
  ideal_para = excluded.ideal_para,
  ritmo = excluded.ritmo,
  duracion_dias = excluded.duracion_dias,
  duracion_noches = excluded.duracion_noches,
  fechas_salida = excluded.fechas_salida,
  salida_grupal = excluded.salida_grupal,
  coordinadores = excluded.coordinadores,
  precio_desde = excluded.precio_desde,
  moneda = excluded.moneda,
  base_precio = excluded.base_precio,
  vigencia_precio = excluded.vigencia_precio,
  incluye_vuelo = excluded.incluye_vuelo,
  incluye = excluded.incluye,
  no_incluye = excluded.no_incluye,
  itinerario = excluded.itinerario,
  alojamiento = excluded.alojamiento,
  highlights = excluded.highlights,
  imagen_portada = excluded.imagen_portada,
  galeria = excluded.galeria,
  documentacion = excluded.documentacion,
  bases_y_condiciones = excluded.bases_y_condiciones,
  faq = excluded.faq,
  tags = excluded.tags,
  es_ejemplo = excluded.es_ejemplo,
  estado = excluded.estado,
  destacado = excluded.destacado,
  ultimos_lugares = excluded.ultimos_lugares,
  actualizado_por_nombre = excluded.actualizado_por_nombre,
  actualizado_en = now();

-- Europa clásica: Madrid, París y Roma en grupo
insert into public.paquetes (
  slug,
  titulo,
  destino,
  pais,
  region,
  tipo_viaje,
  ideal_para,
  ritmo,
  duracion_dias,
  duracion_noches,
  fechas_salida,
  salida_grupal,
  coordinadores,
  precio_desde,
  moneda,
  base_precio,
  vigencia_precio,
  incluye_vuelo,
  incluye,
  no_incluye,
  itinerario,
  alojamiento,
  highlights,
  imagen_portada,
  galeria,
  documentacion,
  bases_y_condiciones,
  faq,
  tags,
  es_ejemplo,
  estado,
  destacado,
  ultimos_lugares,
  actualizado_por_nombre
) values (
  'europa-clasica-madrid-paris-roma',
  'Europa clásica: Madrid, París y Roma en grupo',
  'Madrid, París y Roma',
  'España, Francia e Italia',
  'europa',
  ARRAY['cultura', 'ciudad', 'gastronomia']::text[],
  ARRAY['pareja', 'amigos', 'adultos-mayores', 'grupo']::text[],
  'intenso',
  14,
  13,
  '["2027-04-10","2027-09-18"]'::jsonb,
  true,
  ARRAY['Silvia Ayala', 'Rodrigo Palma']::text[],
  3480,
  'USD',
  'por persona en base doble',
  '2026-12-20',
  true,
  '["Pasaje aéreo Asunción – Madrid // Roma – Asunción con equipaje de 23 kg","Tren de alta velocidad Madrid – París y vuelo interno París – Roma","13 noches en hoteles 4 estrellas céntricos con desayuno buffet","Coordinador paraguayo acompañando al grupo durante todo el viaje","Visitas panorámicas con guía local en Madrid, París y Roma","Entrada al Museo del Louvre y a los Museos Vaticanos con horario reservado","Traslados de todos los aeropuertos y estaciones","Asistencia al viajero con cobertura Schengen","Impuestos aéreos y tasas de embarque"]'::jsonb,
  '["Almuerzos y cenas, salvo la cena de bienvenida en Madrid","Excursiones opcionales (Toledo, Versalles, Pompeya)","City tax de los hoteles, que se abona en destino (aproximadamente 4 a 7 euros por noche)","Propinas a guías y choferes","Gastos personales"]'::jsonb,
  '[{"dia":1,"titulo":"Asunción – Madrid","descripcion":"Encuentro con el coordinador en el aeropuerto de Asunción y salida rumbo a Madrid. Noche a bordo."},{"dia":2,"titulo":"Llegada a Madrid","descripcion":"Llegada, traslado al hotel y tiempo para descansar del vuelo. A la tarde, primera caminata por la Puerta del Sol y la Plaza Mayor. Cena de bienvenida con todo el grupo."},{"dia":3,"titulo":"Madrid a fondo","descripcion":"Visita panorámica con guía local: Palacio Real, Gran Vía, barrio de las Letras y Parque del Retiro. Tarde libre para el Museo del Prado o para perderse en el Rastro."},{"dia":4,"titulo":"Madrid / Toledo (opcional)","descripcion":"Día libre. Recomendamos la excursión opcional a Toledo, la ciudad de las tres culturas, a una hora de Madrid."},{"dia":5,"titulo":"Madrid – París en tren","descripcion":"Traslado a la estación y viaje en tren de alta velocidad a París. Llegada, traslado al hotel y tarde libre."},{"dia":6,"titulo":"París panorámica","descripcion":"Visita con guía local: Torre Eiffel, Campos Elíseos, Arco del Triunfo, Notre Dame y Barrio Latino. A la noche, opción de paseo en bateau mouche por el Sena."},{"dia":7,"titulo":"Museo del Louvre","descripcion":"Entrada con horario reservado al Louvre por la mañana, con tiempo para las obras principales. Tarde libre en Montmartre y el Sacré-Cœur."},{"dia":8,"titulo":"París / Versalles (opcional)","descripcion":"Día libre. Excursión opcional al Palacio de Versalles y sus jardines."},{"dia":9,"titulo":"París – Roma","descripcion":"Traslado al aeropuerto y vuelo a Roma. Llegada, traslado al hotel y primera caminata por la Fontana di Trevi y la Plaza de España."},{"dia":10,"titulo":"Roma imperial","descripcion":"Visita con guía local al Coliseo, Foro Romano y Palatino. Tarde libre en el Trastevere."},{"dia":11,"titulo":"Vaticano","descripcion":"Entrada con horario reservado a los Museos Vaticanos, la Capilla Sixtina y la Basílica de San Pedro. Tarde libre."},{"dia":12,"titulo":"Roma libre / Pompeya (opcional)","descripcion":"Día libre. Excursión opcional de día completo a Pompeya y la costa napolitana."},{"dia":13,"titulo":"Último día en Roma","descripcion":"Mañana libre para compras y para despedirse de la ciudad. A la tarde, traslado al aeropuerto."},{"dia":14,"titulo":"Llegada a Asunción","descripcion":"Llegada a Asunción y fin de nuestros servicios."}]'::jsonb,
  '[{"nombre":"Hotel Mayorazgo","categoria":"4 estrellas","noches":4,"ciudad":"Madrid"},{"nombre":"Hôtel Mercure La Sorbonne","categoria":"4 estrellas","noches":4,"ciudad":"París"},{"nombre":"Hotel Diocleziano","categoria":"4 estrellas","noches":5,"ciudad":"Roma"}]'::jsonb,
  '["Salida grupal con coordinador paraguayo de principio a fin","Tres capitales en un solo viaje, sin tener que organizar nada","Louvre y Museos Vaticanos con entrada reservada, sin filas eternas","Hoteles 4 estrellas en zonas céntricas, para salir caminando","Tren de alta velocidad Madrid – París incluido"]'::jsonb,
  '{"src":"/muestra/europa-portada.svg","alt":"Ilustración del perfil de una ciudad europea con edificios de distintas alturas al atardecer"}'::jsonb,
  '[{"src":"/muestra/europa-1.svg","alt":"Ilustración de una silueta urbana con torres y cúpulas"},{"src":"/muestra/europa-2.svg","alt":"Ilustración de un edificio histórico con frontón triangular"},{"src":"/muestra/europa-3.svg","alt":"Ilustración de un casco urbano denso bajo un cielo cálido"}]'::jsonb,
  '[{"titulo":"Pasaporte","detalle":"Obligatorio, con validez mínima de 6 meses desde la fecha de regreso y al menos dos páginas libres."},{"titulo":"Visa","detalle":"Los ciudadanos paraguayos no necesitan visa para estadías turísticas de hasta 90 días en el espacio Schengen."},{"titulo":"Autorización ETIAS","detalle":"A partir de su entrada en vigencia, se requerirá la autorización electrónica ETIAS. Nosotros te avisamos y te ayudamos a tramitarla cuando corresponda."},{"titulo":"Seguro médico","detalle":"El espacio Schengen exige cobertura médica mínima. Ya está incluida en el paquete con la asistencia al viajero."},{"titulo":"Vacunas","detalle":"No se exigen vacunas para ingresar a España, Francia ni Italia."}]'::jsonb,
  'Precios expresados en dólares americanos por persona en base doble, sujetos a disponibilidad y a confirmación al momento de la reserva. La salida grupal requiere un mínimo de 15 pasajeros; de no alcanzarse, Palma Travel podrá reprogramar la fecha o reintegrar la totalidad de lo abonado. Las tarifas aéreas pueden variar hasta la emisión de los pasajes. La reserva se confirma con una seña de 800 dólares por persona y el saldo debe abonarse 45 días antes de la salida. Cancelaciones con más de 60 días de anticipación: se retiene la seña. Entre 60 y 30 días: se retiene el 50%. Con menos de 30 días o no presentación: sin reintegro. El orden de las visitas puede modificarse por razones operativas sin alterar el contenido del programa. Los servicios no utilizados no son reembolsables. Palma Travel actúa como intermediario entre el pasajero y los prestadores de servicios, por lo que no se responsabiliza por hechos ajenos a su control. Es responsabilidad del pasajero contar con la documentación exigida por los países de destino.',
  '[{"pregunta":"¿Qué hace el coordinador?","respuesta":"Viaja con el grupo desde Asunción y vuelve con el grupo. Se ocupa del check in, los traslados, los horarios y de resolver cualquier imprevisto, para que vos solo te dediques a disfrutar."},{"pregunta":"¿Puedo viajar solo y compartir habitación?","respuesta":"Sí. Si viajás solo te buscamos a alguien del grupo para compartir. Si preferís habitación individual, tiene un suplemento."},{"pregunta":"¿Cuánto hay que caminar por día?","respuesta":"Es un viaje de ritmo intenso: hay días de 12.000 a 15.000 pasos. Recomendamos calzado cómodo. Si necesitás un ritmo más tranquilo, podemos armarte el mismo recorrido a tu medida."},{"pregunta":"¿Cuándo conviene reservar?","respuesta":"Cuanto antes mejor. Los cupos de las salidas grupales son limitados y las tarifas aéreas suben a medida que se acerca la fecha."}]'::jsonb,
  ARRAY['europa', 'madrid', 'paris', 'roma', 'grupal', 'coordinador', 'cultura', 'museos']::text[],
  true,
  'activo',
  true,
  true,
  'Carga inicial'
)
on conflict (slug) do update set
  titulo = excluded.titulo,
  destino = excluded.destino,
  pais = excluded.pais,
  region = excluded.region,
  tipo_viaje = excluded.tipo_viaje,
  ideal_para = excluded.ideal_para,
  ritmo = excluded.ritmo,
  duracion_dias = excluded.duracion_dias,
  duracion_noches = excluded.duracion_noches,
  fechas_salida = excluded.fechas_salida,
  salida_grupal = excluded.salida_grupal,
  coordinadores = excluded.coordinadores,
  precio_desde = excluded.precio_desde,
  moneda = excluded.moneda,
  base_precio = excluded.base_precio,
  vigencia_precio = excluded.vigencia_precio,
  incluye_vuelo = excluded.incluye_vuelo,
  incluye = excluded.incluye,
  no_incluye = excluded.no_incluye,
  itinerario = excluded.itinerario,
  alojamiento = excluded.alojamiento,
  highlights = excluded.highlights,
  imagen_portada = excluded.imagen_portada,
  galeria = excluded.galeria,
  documentacion = excluded.documentacion,
  bases_y_condiciones = excluded.bases_y_condiciones,
  faq = excluded.faq,
  tags = excluded.tags,
  es_ejemplo = excluded.es_ejemplo,
  estado = excluded.estado,
  destacado = excluded.destacado,
  ultimos_lugares = excluded.ultimos_lugares,
  actualizado_por_nombre = excluded.actualizado_por_nombre,
  actualizado_en = now();

-- Misiones jesuíticas y Encarnación: Paraguay de fin de semana
insert into public.paquetes (
  slug,
  titulo,
  destino,
  pais,
  region,
  tipo_viaje,
  ideal_para,
  ritmo,
  duracion_dias,
  duracion_noches,
  fechas_salida,
  salida_grupal,
  coordinadores,
  precio_desde,
  moneda,
  base_precio,
  vigencia_precio,
  incluye_vuelo,
  incluye,
  no_incluye,
  itinerario,
  alojamiento,
  highlights,
  imagen_portada,
  galeria,
  documentacion,
  bases_y_condiciones,
  faq,
  tags,
  es_ejemplo,
  estado,
  destacado,
  ultimos_lugares,
  actualizado_por_nombre
) values (
  'misiones-jesuiticas-encarnacion',
  'Misiones jesuíticas y Encarnación: Paraguay de fin de semana',
  'Encarnación, Trinidad y Jesús',
  'Paraguay',
  'paraguay',
  ARRAY['cultura', 'naturaleza', 'gastronomia']::text[],
  ARRAY['familia', 'pareja', 'amigos', 'adultos-mayores']::text[],
  'tranquilo',
  3,
  2,
  '"flexible"'::jsonb,
  false,
  '{}'::text[],
  210,
  'USD',
  'por persona en base doble',
  '2026-12-31',
  false,
  '["Transporte terrestre ida y vuelta desde Asunción en bus ejecutivo","2 noches de alojamiento en Encarnación con desayuno","Visita guiada a las ruinas de Trinidad y Jesús de Tavarangüé, con entradas incluidas","Espectáculo de luz y sonido en Trinidad","Tarde en la playa San José sobre el río Paraná","Guía acompañante durante todo el recorrido"]'::jsonb,
  '["Pasaje aéreo: este paquete es 100% terrestre, la salida es en bus desde Asunción","Almuerzos y cenas","Excursión a la Ruta de la Yerba Mate y a Bella Vista (opcional)","Gastos personales"]'::jsonb,
  '[{"dia":1,"titulo":"Asunción – Encarnación","descripcion":"Salida temprano desde Asunción en bus ejecutivo. Aproximadamente 5 horas de viaje por la Ruta 1, con parada intermedia. Llegada a Encarnación, check in y tarde libre en la costanera, con su playa urbana y sus food trucks."},{"dia":2,"titulo":"Trinidad y Jesús de Tavarangüé","descripcion":"Día completo en las dos misiones jesuíticas declaradas Patrimonio de la Humanidad por la Unesco. Visita guiada a Trinidad por la mañana y a Jesús de Tavarangüé por la tarde. A la noche, el espectáculo de luz y sonido sobre las ruinas de Trinidad, que se ve de noche y es la postal del viaje."},{"dia":3,"titulo":"Playa San José y regreso","descripcion":"Mañana en la playa San José, sobre el río Paraná. Almuerzo libre en la costanera y a la tarde salida de regreso a Asunción."}]'::jsonb,
  '[{"nombre":"Hotel de la Costa","categoria":"3 estrellas","noches":2,"ciudad":"Encarnación"}]'::jsonb,
  '["Dos sitios Patrimonio de la Humanidad de la Unesco en un fin de semana","El espectáculo de luz y sonido de Trinidad, de noche, incluido","Sin trámites ni pasaporte: todo dentro de Paraguay","Ideal para escaparse tres días sin pedir muchos días de vacaciones"]'::jsonb,
  '{"src":"/muestra/misiones-portada.svg","alt":"Ilustración de una construcción antigua de piedra con frontón, recortada contra un cielo cálido"}'::jsonb,
  '[{"src":"/muestra/misiones-1.svg","alt":"Ilustración de vegetación densa y copas de árboles al atardecer"},{"src":"/muestra/misiones-2.svg","alt":"Ilustración de ruinas de piedra bajo el sol"},{"src":"/muestra/misiones-3.svg","alt":"Ilustración de una costa de río con vegetación baja"}]'::jsonb,
  '[{"titulo":"Documento de identidad","detalle":"Cédula de identidad paraguaya vigente. Es un viaje dentro del país, no se necesita pasaporte."},{"titulo":"Si querés cruzar a Posadas","detalle":"Encarnación está unida a Posadas (Argentina) por el puente San Roque González. Si querés cruzar en tu tiempo libre, necesitás la cédula vigente. No está incluido en el programa."},{"titulo":"Vacunas","detalle":"No se exigen vacunas. Llevá repelente y protector solar."}]'::jsonb,
  'Precios expresados en dólares americanos por persona en base doble, sujetos a disponibilidad y a confirmación al momento de la reserva. También se puede abonar en guaraníes al tipo de cambio del día. Este paquete NO incluye pasaje aéreo: el traslado desde Asunción es terrestre, en bus ejecutivo. La salida es flexible y se coordina según la fecha que elija el pasajero, con un mínimo de 2 pasajeros. El espectáculo de luz y sonido de Trinidad depende de las condiciones climáticas y de la programación del sitio; si se suspende, se reprograma dentro de la estadía o se reintegra el valor de la entrada. Cancelaciones con más de 15 días de anticipación: sin gastos. Entre 15 y 7 días: se retiene el 30%. Con menos de 7 días o no presentación: se retiene el 100%. Los servicios no utilizados no son reembolsables. Palma Travel actúa como intermediario entre el pasajero y los prestadores de servicios, por lo que no se responsabiliza por hechos ajenos a su control.',
  '[{"pregunta":"¿Este paquete incluye vuelo?","respuesta":"No. Es un viaje terrestre: salimos de Asunción en bus ejecutivo y son unas 5 horas hasta Encarnación. Está pensado así para que sea accesible."},{"pregunta":"¿Puedo ir en mi propio auto?","respuesta":"Sí. Si preferís manejar, te descontamos el transporte del precio y te armamos el paquete solo con el hotel y las visitas guiadas."},{"pregunta":"¿Se puede hacer en Carnaval?","respuesta":"Sí, y es la época más linda, pero también la más demandada: el Carnaval Encarnaceno llena la ciudad. Hay que reservar con varios meses de anticipación y las tarifas son más altas."},{"pregunta":"¿Es apto para adultos mayores?","respuesta":"Sí. El ritmo es tranquilo, aunque las ruinas tienen superficies irregulares y algo de sol. Recomendamos calzado cómodo, gorro y agua."}]'::jsonb,
  ARRAY['paraguay', 'encarnacion', 'trinidad', 'jesuitas', 'unesco', 'sin vuelo', 'fin de semana', 'economico']::text[],
  true,
  'activo',
  true,
  false,
  'Carga inicial'
)
on conflict (slug) do update set
  titulo = excluded.titulo,
  destino = excluded.destino,
  pais = excluded.pais,
  region = excluded.region,
  tipo_viaje = excluded.tipo_viaje,
  ideal_para = excluded.ideal_para,
  ritmo = excluded.ritmo,
  duracion_dias = excluded.duracion_dias,
  duracion_noches = excluded.duracion_noches,
  fechas_salida = excluded.fechas_salida,
  salida_grupal = excluded.salida_grupal,
  coordinadores = excluded.coordinadores,
  precio_desde = excluded.precio_desde,
  moneda = excluded.moneda,
  base_precio = excluded.base_precio,
  vigencia_precio = excluded.vigencia_precio,
  incluye_vuelo = excluded.incluye_vuelo,
  incluye = excluded.incluye,
  no_incluye = excluded.no_incluye,
  itinerario = excluded.itinerario,
  alojamiento = excluded.alojamiento,
  highlights = excluded.highlights,
  imagen_portada = excluded.imagen_portada,
  galeria = excluded.galeria,
  documentacion = excluded.documentacion,
  bases_y_condiciones = excluded.bases_y_condiciones,
  faq = excluded.faq,
  tags = excluded.tags,
  es_ejemplo = excluded.es_ejemplo,
  estado = excluded.estado,
  destacado = excluded.destacado,
  ultimos_lugares = excluded.ultimos_lugares,
  actualizado_por_nombre = excluded.actualizado_por_nombre,
  actualizado_en = now();

-- Punta Cana all inclusive: siete días sin pensar en nada
insert into public.paquetes (
  slug,
  titulo,
  destino,
  pais,
  region,
  tipo_viaje,
  ideal_para,
  ritmo,
  duracion_dias,
  duracion_noches,
  fechas_salida,
  salida_grupal,
  coordinadores,
  precio_desde,
  moneda,
  base_precio,
  vigencia_precio,
  incluye_vuelo,
  incluye,
  no_incluye,
  itinerario,
  alojamiento,
  highlights,
  imagen_portada,
  galeria,
  documentacion,
  bases_y_condiciones,
  faq,
  tags,
  es_ejemplo,
  estado,
  destacado,
  ultimos_lugares,
  actualizado_por_nombre
) values (
  'punta-cana-todo-incluido',
  'Punta Cana all inclusive: siete días sin pensar en nada',
  'Punta Cana',
  'República Dominicana',
  'caribe',
  ARRAY['playa', 'relax', 'gastronomia']::text[],
  ARRAY['pareja', 'familia', 'amigos']::text[],
  'tranquilo',
  8,
  7,
  '["2026-11-14","2026-12-05","2027-01-16","2027-02-13"]'::jsonb,
  false,
  '{}'::text[],
  1850,
  'USD',
  'por persona en base doble',
  '2026-10-31',
  true,
  '["Pasaje aéreo Asunción – Punta Cana – Asunción con conexiones y equipaje de 23 kg","7 noches en resort 5 estrellas régimen all inclusive (todas las comidas y bebidas incluidas)","Traslados aeropuerto – resort – aeropuerto","Acceso a piscinas, playa privada, gimnasio y actividades del resort","Shows nocturnos y entretenimiento del hotel","Asistencia al viajero con cobertura ampliada","Impuestos aéreos, tasas de embarque y tarjeta de turista"]'::jsonb,
  '["Excursiones fuera del resort (Isla Saona, Hoyo Azul, catamarán)","Tratamientos de spa y deportes acuáticos motorizados","Propinas","Gastos personales"]'::jsonb,
  '[{"dia":1,"titulo":"Asunción – Punta Cana","descripcion":"Salida desde Asunción con conexión. Llegada a Punta Cana, recepción en el aeropuerto y traslado al resort. Check in, pulsera all inclusive y primera cena en el buffet."},{"dia":2,"titulo":"Playa Bávaro","descripcion":"Primer día completo de descanso. Playa de arena blanca, reposeras, piscina y almuerzo en cualquiera de los restaurantes del resort. A la noche, show en el teatro del hotel."},{"dia":3,"titulo":"Día libre","descripcion":"Día libre para disfrutar el resort. Buen momento para reservar una excursión opcional a Isla Saona, que sale temprano al día siguiente."},{"dia":4,"titulo":"Día libre / Isla Saona (opcional)","descripcion":"Día libre. Opcionalmente, excursión de día completo en catamarán y lancha rápida a Isla Saona, con almuerzo y piscina natural en el mar."},{"dia":5,"titulo":"Día libre","descripcion":"Descanso, deportes náuticos sin motor incluidos (kayak, snorkel, windsurf) y restaurantes temáticos a la carta."},{"dia":6,"titulo":"Día libre / Hoyo Azul (opcional)","descripcion":"Día libre. Opción de excursión al parque Scape Park y al cenote Hoyo Azul, con tirolesas y baño en agua turquesa."},{"dia":7,"titulo":"Último día completo","descripcion":"Último día para aprovechar la playa, el spa o simplemente no hacer nada. Compras de último momento en las tiendas del resort."},{"dia":8,"titulo":"Punta Cana – Asunción","descripcion":"Desayuno, check out y traslado al aeropuerto para el vuelo de regreso a Asunción."}]'::jsonb,
  '[{"nombre":"Grand Bávaro Beach Resort & Spa","categoria":"5 estrellas all inclusive","noches":7,"ciudad":"Punta Cana"}]'::jsonb,
  '["Todo incluido de verdad: comidas, bebidas, snacks y shows","Playa privada en Bávaro, de las mejores del Caribe","Resort apto para chicos, con club infantil y piscinas separadas","Cuatro fechas de salida entre noviembre y febrero","Cobertura de asistencia al viajero ampliada incluida"]'::jsonb,
  '{"src":"/muestra/puntacana-portada.svg","alt":"Ilustración de una playa caribeña con agua turquesa y cielo despejado"}'::jsonb,
  '[{"src":"/muestra/puntacana-1.svg","alt":"Ilustración de una costa tropical de arena blanca"},{"src":"/muestra/puntacana-2.svg","alt":"Ilustración del mar en calma bajo un sol alto"},{"src":"/muestra/puntacana-3.svg","alt":"Ilustración de una laguna turquesa rodeada de vegetación baja"}]'::jsonb,
  '[{"titulo":"Pasaporte","detalle":"Obligatorio, con una validez mínima de 6 meses desde la fecha de regreso."},{"titulo":"Visa","detalle":"Los ciudadanos paraguayos no necesitan visa. La tarjeta de turista está incluida en el precio del paquete."},{"titulo":"Vacunas","detalle":"No hay vacunas obligatorias. Se recomienda repelente de mosquitos y protector solar alto."},{"titulo":"Formulario de entrada","detalle":"República Dominicana pide completar un formulario electrónico de entrada y salida (E-Ticket). Te lo enviamos completado unos días antes del viaje."}]'::jsonb,
  'Precios expresados en dólares americanos por persona en base doble, sujetos a disponibilidad y a confirmación al momento de la reserva. Las tarifas aéreas pueden variar hasta la emisión de los pasajes. La reserva se confirma con una seña del 30% y el saldo debe abonarse 30 días antes de la salida. Cancelaciones con más de 45 días de anticipación: se retiene el 15% en concepto de gastos administrativos. Entre 45 y 21 días: se retiene el 50%. Con menos de 21 días o no presentación: sin reintegro. El régimen all inclusive comienza con el check in y finaliza con el check out según las políticas del resort. Los servicios no utilizados no son reembolsables. Palma Travel actúa como intermediario entre el pasajero y los prestadores de servicios, por lo que no se responsabiliza por hechos ajenos a su control. Es responsabilidad del pasajero contar con la documentación exigida por el país de destino.',
  '[{"pregunta":"¿Cuántas escalas tiene el vuelo?","respuesta":"Según la fecha, una o dos escalas, normalmente por São Paulo o Panamá. Te confirmamos la ruta exacta antes de reservar."},{"pregunta":"¿Los chicos pagan lo mismo?","respuesta":"No. Los menores compartiendo habitación con dos adultos tienen tarifa reducida y según la edad pueden ser gratis. Escribinos con las edades y te pasamos el precio exacto."},{"pregunta":"¿Las bebidas alcohólicas están incluidas?","respuesta":"Sí, el régimen all inclusive incluye bebidas nacionales e internacionales sin límite dentro del resort."},{"pregunta":"¿Conviene contratar las excursiones desde acá?","respuesta":"Podés hacerlo con nosotros antes de viajar o en el resort. Reservando con anticipación suele salir algo más barato y te asegurás el cupo."}]'::jsonb,
  ARRAY['caribe', 'all inclusive', 'playa', 'resort', 'luna de miel', 'familia']::text[],
  true,
  'activo',
  true,
  false,
  'Carga inicial'
)
on conflict (slug) do update set
  titulo = excluded.titulo,
  destino = excluded.destino,
  pais = excluded.pais,
  region = excluded.region,
  tipo_viaje = excluded.tipo_viaje,
  ideal_para = excluded.ideal_para,
  ritmo = excluded.ritmo,
  duracion_dias = excluded.duracion_dias,
  duracion_noches = excluded.duracion_noches,
  fechas_salida = excluded.fechas_salida,
  salida_grupal = excluded.salida_grupal,
  coordinadores = excluded.coordinadores,
  precio_desde = excluded.precio_desde,
  moneda = excluded.moneda,
  base_precio = excluded.base_precio,
  vigencia_precio = excluded.vigencia_precio,
  incluye_vuelo = excluded.incluye_vuelo,
  incluye = excluded.incluye,
  no_incluye = excluded.no_incluye,
  itinerario = excluded.itinerario,
  alojamiento = excluded.alojamiento,
  highlights = excluded.highlights,
  imagen_portada = excluded.imagen_portada,
  galeria = excluded.galeria,
  documentacion = excluded.documentacion,
  bases_y_condiciones = excluded.bases_y_condiciones,
  faq = excluded.faq,
  tags = excluded.tags,
  es_ejemplo = excluded.es_ejemplo,
  estado = excluded.estado,
  destacado = excluded.destacado,
  ultimos_lugares = excluded.ultimos_lugares,
  actualizado_por_nombre = excluded.actualizado_por_nombre,
  actualizado_en = now();

-- Río de Janeiro: playa, samba y Pan de Azúcar
insert into public.paquetes (
  slug,
  titulo,
  destino,
  pais,
  region,
  tipo_viaje,
  ideal_para,
  ritmo,
  duracion_dias,
  duracion_noches,
  fechas_salida,
  salida_grupal,
  coordinadores,
  precio_desde,
  moneda,
  base_precio,
  vigencia_precio,
  incluye_vuelo,
  incluye,
  no_incluye,
  itinerario,
  alojamiento,
  highlights,
  imagen_portada,
  galeria,
  documentacion,
  bases_y_condiciones,
  faq,
  tags,
  es_ejemplo,
  estado,
  destacado,
  ultimos_lugares,
  actualizado_por_nombre
) values (
  'rio-de-janeiro-verano',
  'Río de Janeiro: playa, samba y Pan de Azúcar',
  'Río de Janeiro',
  'Brasil',
  'sudamerica',
  ARRAY['playa', 'ciudad', 'gastronomia']::text[],
  ARRAY['pareja', 'amigos', 'familia']::text[],
  'moderado',
  6,
  5,
  '"flexible"'::jsonb,
  false,
  '{}'::text[],
  890,
  'USD',
  'por persona en base doble',
  '2026-11-30',
  true,
  '["Pasaje aéreo Asunción – Río de Janeiro – Asunción con equipaje de mano y una valija de 23 kg","5 noches de alojamiento en Copacabana con desayuno buffet","Traslados aeropuerto – hotel – aeropuerto en servicio compartido","Excursión de día completo al Cristo Redentor y Pan de Azúcar con guía en español","Asistencia al viajero por todo el período del viaje","Impuestos aéreos y tasas de embarque"]'::jsonb,
  '["Almuerzos y cenas, salvo lo indicado","Excursiones opcionales (Petrópolis, favela tour, paseo en barco)","Propinas a guías y choferes","Gastos personales"]'::jsonb,
  '[{"dia":1,"titulo":"Asunción – Río de Janeiro","descripcion":"Salida desde el Aeropuerto Silvio Pettirossi. Llegada a Río, recepción en el aeropuerto y traslado al hotel en Copacabana. Resto del día libre para dar la primera caminata por la orilla y comer un açaí frente al mar."},{"dia":2,"titulo":"Cristo Redentor y Pan de Azúcar","descripcion":"Día completo de visita. Subida en tren al Corcovado para ver el Cristo Redentor y toda la bahía desde arriba. Por la tarde, teleférico al Morro da Urca y al Pan de Azúcar para el atardecer. Guía en español."},{"dia":3,"titulo":"Día libre de playa","descripcion":"Día entero para disfrutar Copacabana e Ipanema a tu ritmo. Te dejamos recomendaciones de dónde alquilar sombrilla, dónde comer bien sin gastar de más y cómo llegar caminando al Arpoador para ver la puesta de sol."},{"dia":4,"titulo":"Centro histórico y Santa Teresa","descripcion":"Mañana libre. Sugerimos recorrer la Escalera de Selarón, el barrio bohemio de Santa Teresa y el Theatro Municipal. A la noche, opción de cena con show de samba en Lapa (opcional)."},{"dia":5,"titulo":"Día libre","descripcion":"Último día completo. Buen momento para una excursión opcional a Petrópolis, un paseo en barco por la bahía de Guanabara o simplemente más playa y compras en Ipanema."},{"dia":6,"titulo":"Río de Janeiro – Asunción","descripcion":"Desayuno en el hotel, tiempo libre según el horario del vuelo y traslado al aeropuerto para el regreso a Asunción."}]'::jsonb,
  '[{"nombre":"Hotel Astoria Copacabana","categoria":"3 estrellas superior","noches":5,"ciudad":"Río de Janeiro"}]'::jsonb,
  '["Cristo Redentor y Pan de Azúcar en un solo día, con guía en español","Hotel a una cuadra de la playa de Copacabana","Dos días enteros libres para hacer tu propio plan","Vuelo directo desde Asunción incluido"]'::jsonb,
  '{"src":"/muestra/rio-portada.svg","alt":"Ilustración de una costa tropical al atardecer, con el sol bajo sobre el mar"}'::jsonb,
  '[{"src":"/muestra/rio-1.svg","alt":"Ilustración del perfil de una ciudad con edificios altos contra el cielo"},{"src":"/muestra/rio-2.svg","alt":"Ilustración de una playa de arena clara con el mar en calma"},{"src":"/muestra/rio-3.svg","alt":"Ilustración de cerros verdes recortados sobre un cielo cálido"}]'::jsonb,
  '[{"titulo":"Documento de identidad","detalle":"Los paraguayos pueden entrar a Brasil con la cédula de identidad vigente y en buen estado, o con el pasaporte. Para menores de edad que viajan sin uno de los padres se necesita autorización."},{"titulo":"Visa","detalle":"No se necesita visa para ciudadanos paraguayos."},{"titulo":"Vacunas","detalle":"No es obligatoria, pero se recomienda la vacuna contra la fiebre amarilla al menos 10 días antes del viaje."}]'::jsonb,
  'Precios expresados en dólares americanos por persona en base doble, sujetos a disponibilidad y a confirmación al momento de la reserva. Las tarifas aéreas pueden variar hasta la emisión de los pasajes. La reserva se confirma con una seña del 30% y el saldo debe abonarse 21 días antes de la salida. Cancelaciones con más de 30 días de anticipación: se retiene el 10% en concepto de gastos administrativos. Entre 30 y 15 días: se retiene el 50%. Con menos de 15 días o no presentación: sin reintegro. Los servicios no utilizados durante el viaje no son reembolsables ni canjeables. Palma Travel actúa como intermediario entre el pasajero y los prestadores de servicios (aerolíneas, hoteles, operadores terrestres), por lo que no se responsabiliza por hechos ajenos a su control como demoras, cancelaciones o modificaciones dispuestas por dichos prestadores, condiciones climáticas o causas de fuerza mayor. Es responsabilidad del pasajero contar con la documentación exigida por el país de destino.',
  '[{"pregunta":"¿El vuelo sale de Asunción?","respuesta":"Sí, todas nuestras salidas son desde el Aeropuerto Internacional Silvio Pettirossi. Si viajás desde el interior, te ayudamos a coordinar la conexión."},{"pregunta":"¿Puedo agregar noches?","respuesta":"Sí. El paquete es de salida flexible, así que podemos armarlo con las noches que quieras y ajustamos el precio."},{"pregunta":"¿Se puede pagar en cuotas?","respuesta":"Sí, trabajamos con las principales tarjetas y podemos armarte un plan de pagos. Escribinos y te pasamos las opciones."}]'::jsonb,
  ARRAY['brasil', 'playa', 'copacabana', 'cristo redentor', 'verano', 'escapada']::text[],
  true,
  'activo',
  true,
  false,
  'Carga inicial'
)
on conflict (slug) do update set
  titulo = excluded.titulo,
  destino = excluded.destino,
  pais = excluded.pais,
  region = excluded.region,
  tipo_viaje = excluded.tipo_viaje,
  ideal_para = excluded.ideal_para,
  ritmo = excluded.ritmo,
  duracion_dias = excluded.duracion_dias,
  duracion_noches = excluded.duracion_noches,
  fechas_salida = excluded.fechas_salida,
  salida_grupal = excluded.salida_grupal,
  coordinadores = excluded.coordinadores,
  precio_desde = excluded.precio_desde,
  moneda = excluded.moneda,
  base_precio = excluded.base_precio,
  vigencia_precio = excluded.vigencia_precio,
  incluye_vuelo = excluded.incluye_vuelo,
  incluye = excluded.incluye,
  no_incluye = excluded.no_incluye,
  itinerario = excluded.itinerario,
  alojamiento = excluded.alojamiento,
  highlights = excluded.highlights,
  imagen_portada = excluded.imagen_portada,
  galeria = excluded.galeria,
  documentacion = excluded.documentacion,
  bases_y_condiciones = excluded.bases_y_condiciones,
  faq = excluded.faq,
  tags = excluded.tags,
  es_ejemplo = excluded.es_ejemplo,
  estado = excluded.estado,
  destacado = excluded.destacado,
  ultimos_lugares = excluded.ultimos_lugares,
  actualizado_por_nombre = excluded.actualizado_por_nombre,
  actualizado_en = now();

-- Peregrinación a Tierra Santa con acompañamiento espiritual
insert into public.paquetes (
  slug,
  titulo,
  destino,
  pais,
  region,
  tipo_viaje,
  ideal_para,
  ritmo,
  duracion_dias,
  duracion_noches,
  fechas_salida,
  salida_grupal,
  coordinadores,
  precio_desde,
  moneda,
  base_precio,
  vigencia_precio,
  incluye_vuelo,
  incluye,
  no_incluye,
  itinerario,
  alojamiento,
  highlights,
  imagen_portada,
  galeria,
  documentacion,
  bases_y_condiciones,
  faq,
  tags,
  es_ejemplo,
  estado,
  destacado,
  ultimos_lugares,
  actualizado_por_nombre
) values (
  'tierra-santa-peregrinacion',
  'Peregrinación a Tierra Santa con acompañamiento espiritual',
  'Jerusalén, Belén, Nazaret y Galilea',
  'Israel',
  'otros',
  ARRAY['religioso', 'cultura']::text[],
  ARRAY['adultos-mayores', 'grupo', 'solo', 'pareja']::text[],
  'moderado',
  11,
  10,
  '["2027-03-06"]'::jsonb,
  true,
  ARRAY['Padre Ignacio Duarte', 'Marta Giménez']::text[],
  3990,
  'USD',
  'por persona en base doble',
  '2026-11-15',
  true,
  '["Pasaje aéreo Asunción – Tel Aviv – Asunción con conexiones y equipaje de 23 kg","10 noches en hoteles 4 estrellas en Jerusalén, Belén y Galilea, con media pensión (desayuno y cena)","Todos los traslados y recorridos en bus con aire acondicionado","Guía local especializado en Tierra Santa, en español","Acompañamiento espiritual: misa diaria en los santuarios del itinerario","Entradas a todos los sitios del programa","Renovación de las promesas matrimoniales en Caná para los matrimonios del grupo","Asistencia al viajero y propinas a guía y chofer","Impuestos aéreos y tasas de embarque"]'::jsonb,
  '["Almuerzos","Bebidas en las cenas","Gastos personales y ofrendas"]'::jsonb,
  '[{"dia":1,"titulo":"Asunción – Tel Aviv","descripcion":"Encuentro en el aeropuerto de Asunción con el Padre Ignacio y la coordinadora. Bendición de salida y comienzo del viaje. Noche a bordo."},{"dia":2,"titulo":"Llegada y traslado a Galilea","descripcion":"Llegada a Tel Aviv, recepción y traslado hacia Galilea bordeando la costa mediterránea. Check in y cena. Primera oración del grupo a orillas del lago."},{"dia":3,"titulo":"Nazaret y Caná","descripcion":"Basílica de la Anunciación en Nazaret e iglesia de San José. Por la tarde, Caná de Galilea, con la renovación de las promesas matrimoniales. Misa."},{"dia":4,"titulo":"Mar de Galilea","descripcion":"Navegación por el lago de Tiberíades, Cafarnaúm, el Monte de las Bienaventuranzas y Tabgha, lugar de la multiplicación de los panes y los peces. Misa en las Bienaventuranzas."},{"dia":5,"titulo":"Monte Tabor y Jordán","descripcion":"Subida al Monte Tabor, lugar de la Transfiguración. Renovación de las promesas bautismales en el río Jordán. Traslado a Belén."},{"dia":6,"titulo":"Belén","descripcion":"Basílica de la Natividad, la gruta donde nació Jesús, y el Campo de los Pastores. Tarde para visitar los talleres de artesanos locales. Misa en Belén."},{"dia":7,"titulo":"Jerusalén: Monte de los Olivos","descripcion":"Monte de los Olivos, Getsemaní, la Basílica de la Agonía y la iglesia del Pater Noster. Vista completa de la ciudad vieja desde el Dominus Flevit."},{"dia":8,"titulo":"Vía Dolorosa y Santo Sepulcro","descripcion":"Recorrido de las catorce estaciones de la Vía Dolorosa por la ciudad vieja hasta el Santo Sepulcro. Muro de los Lamentos. Misa en el Santo Sepulcro."},{"dia":9,"titulo":"Ein Karem y Monte Sion","descripcion":"Ein Karem, lugar de la Visitación y del nacimiento de Juan el Bautista. Monte Sion, Cenáculo y Dormición de la Virgen."},{"dia":10,"titulo":"Mar Muerto y Jericó","descripcion":"Bajada al Mar Muerto, con tiempo para flotar en sus aguas. Jericó, la ciudad más antigua del mundo, y el Monte de las Tentaciones. Regreso a Jerusalén y cena de despedida."},{"dia":11,"titulo":"Tel Aviv – Asunción","descripcion":"Traslado al aeropuerto de Tel Aviv y regreso a Asunción."}]'::jsonb,
  '[{"nombre":"Hotel Restal","categoria":"4 estrellas","noches":3,"ciudad":"Tiberíades (Galilea)"},{"nombre":"Hotel Bethlehem Star","categoria":"4 estrellas","noches":2,"ciudad":"Belén"},{"nombre":"Hotel Grand Court","categoria":"4 estrellas","noches":5,"ciudad":"Jerusalén"}]'::jsonb,
  '["Misa diaria en los santuarios, con acompañamiento sacerdotal paraguayo","Renovación de las promesas matrimoniales en Caná de Galilea","La Vía Dolorosa completa, a pie, hasta el Santo Sepulcro","Media pensión incluida: desayuno y cena todos los días","Grupo reducido, con coordinadora dedicada al cuidado de los peregrinos"]'::jsonb,
  '{"src":"/muestra/tierrasanta-portada.svg","alt":"Ilustración de un templo de piedra con frontón triangular bajo un cielo dorado"}'::jsonb,
  '[{"src":"/muestra/tierrasanta-1.svg","alt":"Ilustración de una construcción religiosa antigua al amanecer"},{"src":"/muestra/tierrasanta-2.svg","alt":"Ilustración de una ciudad amurallada de casas bajas"},{"src":"/muestra/tierrasanta-3.svg","alt":"Ilustración de una orilla tranquila con vegetación baja"}]'::jsonb,
  '[{"titulo":"Pasaporte","detalle":"Obligatorio, con validez mínima de 6 meses desde la fecha de regreso."},{"titulo":"Visa","detalle":"Los ciudadanos paraguayos no necesitan visa para turismo en Israel. El ingreso se registra electrónicamente."},{"titulo":"Autorización de entrada","detalle":"Israel puede requerir una autorización electrónica de viaje previa. Nosotros la gestionamos para todo el grupo."},{"titulo":"Vacunas","detalle":"No se exigen vacunas."},{"titulo":"Recomendación","detalle":"Para entrar a los santuarios se pide ropa que cubra hombros y rodillas. Llevá un pañuelo o chal liviano."}]'::jsonb,
  'Precios expresados en dólares americanos por persona en base doble, sujetos a disponibilidad y a confirmación al momento de la reserva. Esta salida está AGOTADA: se cerró el cupo de la peregrinación de marzo de 2027. Si te interesa, escribinos y te anotamos en la lista de espera y te avisamos de la próxima fecha. La salida grupal requiere un mínimo de 20 peregrinos. Las tarifas aéreas pueden variar hasta la emisión de los pasajes. La reserva se confirma con una seña de 1.000 dólares por persona y el saldo debe abonarse 60 días antes de la salida. Cancelaciones con más de 90 días de anticipación: se retiene la seña. Entre 90 y 45 días: se retiene el 60%. Con menos de 45 días o no presentación: sin reintegro. El itinerario puede modificarse por razones de seguridad, operativas o litúrgicas, manteniendo el contenido del programa. Los servicios no utilizados no son reembolsables. Palma Travel actúa como intermediario entre el pasajero y los prestadores de servicios, por lo que no se responsabiliza por hechos ajenos a su control. Es responsabilidad del pasajero contar con la documentación exigida por el país de destino.',
  '[{"pregunta":"¿Hay que ser muy católico practicante?","respuesta":"No hace falta. Es una peregrinación con misa diaria y acompañamiento espiritual, pero recibimos a todo el que quiera conocer los lugares con respeto. Las misas son opcionales."},{"pregunta":"¿Cuánto se camina?","respuesta":"El ritmo es moderado. Los días más exigentes son el de la Vía Dolorosa y el del Monte Tabor, con escaleras y empedrado. La mayor parte del grupo son adultos mayores y el recorrido está pensado para eso."},{"pregunta":"¿Por qué está agotado?","respuesta":"El cupo de la salida de marzo de 2027 ya se completó. Escribinos por WhatsApp y te anotamos en la lista de espera para esa fecha o para la próxima peregrinación."},{"pregunta":"¿Es seguro viajar a Tierra Santa?","respuesta":"Seguimos permanentemente las recomendaciones oficiales y las de nuestro operador local. Si la situación lo desaconseja, reprogramamos la salida o devolvemos lo abonado, como dice en las bases y condiciones."}]'::jsonb,
  ARRAY['peregrinacion', 'religioso', 'tierra santa', 'jerusalen', 'belen', 'grupal', 'coordinador', 'israel']::text[],
  true,
  'agotado',
  false,
  false,
  'Carga inicial'
)
on conflict (slug) do update set
  titulo = excluded.titulo,
  destino = excluded.destino,
  pais = excluded.pais,
  region = excluded.region,
  tipo_viaje = excluded.tipo_viaje,
  ideal_para = excluded.ideal_para,
  ritmo = excluded.ritmo,
  duracion_dias = excluded.duracion_dias,
  duracion_noches = excluded.duracion_noches,
  fechas_salida = excluded.fechas_salida,
  salida_grupal = excluded.salida_grupal,
  coordinadores = excluded.coordinadores,
  precio_desde = excluded.precio_desde,
  moneda = excluded.moneda,
  base_precio = excluded.base_precio,
  vigencia_precio = excluded.vigencia_precio,
  incluye_vuelo = excluded.incluye_vuelo,
  incluye = excluded.incluye,
  no_incluye = excluded.no_incluye,
  itinerario = excluded.itinerario,
  alojamiento = excluded.alojamiento,
  highlights = excluded.highlights,
  imagen_portada = excluded.imagen_portada,
  galeria = excluded.galeria,
  documentacion = excluded.documentacion,
  bases_y_condiciones = excluded.bases_y_condiciones,
  faq = excluded.faq,
  tags = excluded.tags,
  es_ejemplo = excluded.es_ejemplo,
  estado = excluded.estado,
  destacado = excluded.destacado,
  ultimos_lugares = excluded.ultimos_lugares,
  actualizado_por_nombre = excluded.actualizado_por_nombre,
  actualizado_en = now();

-- -------------------------------------------------------------------
-- PROPUESTAS PERSONALIZADAS (1)
-- -------------------------------------------------------------------

-- Familia González — El Calafate y El Chaltén: glaciares y montaña para la Familia González
insert into public.propuestas (
  slug,
  titulo,
  destino,
  pais,
  region,
  tipo_viaje,
  ideal_para,
  ritmo,
  duracion_dias,
  duracion_noches,
  fechas_salida,
  salida_grupal,
  coordinadores,
  precio_desde,
  moneda,
  base_precio,
  vigencia_precio,
  incluye_vuelo,
  incluye,
  no_incluye,
  itinerario,
  alojamiento,
  highlights,
  imagen_portada,
  galeria,
  documentacion,
  bases_y_condiciones,
  faq,
  tags,
  es_ejemplo,
  cliente_nombre,
  valida_hasta,
  notas_internas,
  actualizado_por_nombre
) values (
  'familia-gonzalez-patagonia',
  'El Calafate y El Chaltén: glaciares y montaña para la Familia González',
  'El Calafate y El Chaltén',
  'Argentina',
  'sudamerica',
  ARRAY['naturaleza', 'aventura', 'relax']::text[],
  ARRAY['familia']::text[],
  'moderado',
  8,
  7,
  '["2026-12-27"]'::jsonb,
  false,
  '{}'::text[],
  1620,
  'USD',
  'por persona, en dos habitaciones dobles (4 pasajeros)',
  '2026-10-31',
  true,
  '["Pasajes aéreos para 4 pasajeros: Asunción – El Calafate – Asunción vía Buenos Aires, con equipaje de 23 kg cada uno","4 noches en El Calafate y 3 noches en El Chaltén, en dos habitaciones dobles con desayuno","Todos los traslados: aeropuerto, hoteles y el tramo El Calafate – El Chaltén ida y vuelta","Excursión al Glaciar Perito Moreno con pasarelas y entrada al Parque Nacional Los Glaciares","Navegación Todo Glaciares por el Lago Argentino (Upsala y Spegazzini)","Caminata guiada al Mirador de los Cóndores y al Chorrillo del Salto en El Chaltén","Asistencia al viajero para los 4 pasajeros","Impuestos aéreos y tasas de embarque"]'::jsonb,
  '["Almuerzos y cenas","Minitrekking sobre el glaciar (lo dejamos afuera a pedido de ustedes)","Excursiones no mencionadas","Gastos personales"]'::jsonb,
  '[{"dia":1,"titulo":"Asunción – El Calafate","descripcion":"Salida de Asunción con conexión en Buenos Aires. Llegada a El Calafate a media tarde, traslado al hotel y caminata tranquila por la avenida principal para conocer el pueblo."},{"dia":2,"titulo":"Glaciar Perito Moreno","descripcion":"Día completo en el Parque Nacional Los Glaciares. Recorrido por las pasarelas frente al Perito Moreno, con distintos miradores y varias horas para escuchar los desprendimientos de hielo. Las pasarelas tienen tramos con ascensor y opciones sin escaleras."},{"dia":3,"titulo":"Navegación Todo Glaciares","descripcion":"Navegación de día completo por el Lago Argentino hasta los glaciares Upsala y Spegazzini, entre témpanos. Es un día de barco, sin caminatas."},{"dia":4,"titulo":"El Calafate libre","descripcion":"Día libre. Sugerencias: la Reserva Laguna Nimez para ver flamencos, el Glaciarium o simplemente descansar antes de subir a El Chaltén."},{"dia":5,"titulo":"El Calafate – El Chaltén","descripcion":"Traslado de unas 3 horas hasta El Chaltén, la capital nacional del trekking, con el Fitz Roy de fondo. Check in y tarde libre en el pueblo."},{"dia":6,"titulo":"Mirador de los Cóndores","descripcion":"Caminata guiada corta, de una hora de subida suave, al Mirador de los Cóndores y de las Águilas, con vista a todo el valle del río de las Vueltas. Tarde libre."},{"dia":7,"titulo":"Chorrillo del Salto","descripcion":"Caminata tranquila y casi sin desnivel hasta la cascada Chorrillo del Salto, entre bosque de lengas. A la tarde, regreso a El Calafate."},{"dia":8,"titulo":"El Calafate – Asunción","descripcion":"Traslado al aeropuerto de El Calafate y regreso a Asunción vía Buenos Aires."}]'::jsonb,
  '[{"nombre":"Hotel Kau Yatun","categoria":"4 estrellas","noches":4,"ciudad":"El Calafate"},{"nombre":"Hostería Senderos","categoria":"3 estrellas superior","noches":3,"ciudad":"El Chaltén"}]'::jsonb,
  '["El Perito Moreno con un día entero, sin apuro","Navegación a Upsala y Spegazzini, un día completo sin caminar","Dos caminatas cortas y suaves en El Chaltén, elegidas para que todos las puedan hacer","Dos habitaciones dobles reservadas, todo cerrado de antemano","Salida el 27 de diciembre, para pasar Año Nuevo en la Patagonia"]'::jsonb,
  '{"src":"/muestra/patagonia-portada.svg","alt":"Ilustración de picos de montaña afilados bajo un cielo claro"}'::jsonb,
  '[{"src":"/muestra/patagonia-1.svg","alt":"Ilustración de una cadena de montañas con un valle al pie"},{"src":"/muestra/patagonia-2.svg","alt":"Ilustración de bosque bajo con siluetas de árboles"},{"src":"/muestra/patagonia-3.svg","alt":"Ilustración de cumbres nevadas contra un cielo gris claro"}]'::jsonb,
  '[{"titulo":"Documento de identidad","detalle":"Cédula de identidad paraguaya vigente para los cuatro, o pasaporte. Los chicos de 14 y 17 viajan con ustedes, así que no necesitan autorización adicional."},{"titulo":"Visa","detalle":"No se necesita visa para ciudadanos paraguayos."},{"titulo":"Vacunas","detalle":"No se exigen vacunas."},{"titulo":"Qué llevar","detalle":"Aunque sea verano, en la Patagonia hace frío y viento fuerte. Campera rompeviento, abrigo en capas, calzado cerrado con buena suela y protector solar alto."}]'::jsonb,
  'Esta propuesta fue armada especialmente para la Familia González y los precios son válidos hasta el 31 de octubre de 2026. Precios expresados en dólares americanos por persona, calculados sobre la base de 4 pasajeros en dos habitaciones dobles; si cambia la cantidad de pasajeros, el precio se recalcula. Sujeto a disponibilidad y a confirmación al momento de la reserva. Las tarifas aéreas pueden variar hasta la emisión de los pasajes. La reserva se confirma con una seña del 30% y el saldo debe abonarse 30 días antes de la salida. Cancelaciones con más de 45 días de anticipación: se retiene el 15%. Entre 45 y 21 días: se retiene el 50%. Con menos de 21 días o no presentación: sin reintegro. Las excursiones en la Patagonia dependen de las condiciones climáticas y del estado de los caminos y del lago; si una navegación o caminata se suspende por clima, se reprograma dentro de la estadía o se reintegra su valor. Los servicios no utilizados no son reembolsables. Palma Travel actúa como intermediario entre el pasajero y los prestadores de servicios, por lo que no se responsabiliza por hechos ajenos a su control.',
  '[{"pregunta":"¿Se puede agregar el minitrekking sobre el glaciar?","respuesta":"Sí, lo dejamos afuera porque implica caminar unas dos horas sobre hielo con grampones. Si alguno del grupo quiere hacerlo por su cuenta ese día, lo cotizamos aparte."},{"pregunta":"¿Qué pasa si el clima arruina una excursión?","respuesta":"En la Patagonia pasa. Si se suspende por clima, la reprogramamos dentro de los días que están ahí o les devolvemos lo que costó esa excursión."},{"pregunta":"¿Conviene cambiar plata allá?","respuesta":"Llevá dólares en efectivo y cambiá en El Calafate, que tiene mejor cotización que el aeropuerto. Las tarjetas se aceptan en casi todos lados."},{"pregunta":"¿Podemos pagar en cuotas?","respuesta":"Sí. Con la seña del 30% ya queda todo reservado y el resto lo podemos dividir hasta 30 días antes de la salida. Charlamos las opciones por WhatsApp."}]'::jsonb,
  ARRAY['patagonia', 'el calafate', 'el chalten', 'glaciares', 'familia', 'propuesta', 'a medida']::text[],
  true,
  'Familia González',
  '2026-10-31',
  'Ejemplo de propuesta personalizada. Contacto: Marcela, la mamá. Son 4: dos adultos y dos adolescentes de 14 y 17. Presupuesto que manejaron: hasta 6.500 dólares en total. Prefieren no manejar y piden que todo esté cerrado de antemano. Ya viajaron con nosotros a Río en 2025. Ojo: el papá tiene problemas de rodilla, evitar trekkings largos, por eso se sacó el Laguna de los Tres y se puso el Chorrillo del Salto. Tarifa aérea cotizada el 12/09, revalidar antes de confirmar.',
  'Carga inicial'
)
on conflict (slug) do update set
  titulo = excluded.titulo,
  destino = excluded.destino,
  pais = excluded.pais,
  region = excluded.region,
  tipo_viaje = excluded.tipo_viaje,
  ideal_para = excluded.ideal_para,
  ritmo = excluded.ritmo,
  duracion_dias = excluded.duracion_dias,
  duracion_noches = excluded.duracion_noches,
  fechas_salida = excluded.fechas_salida,
  salida_grupal = excluded.salida_grupal,
  coordinadores = excluded.coordinadores,
  precio_desde = excluded.precio_desde,
  moneda = excluded.moneda,
  base_precio = excluded.base_precio,
  vigencia_precio = excluded.vigencia_precio,
  incluye_vuelo = excluded.incluye_vuelo,
  incluye = excluded.incluye,
  no_incluye = excluded.no_incluye,
  itinerario = excluded.itinerario,
  alojamiento = excluded.alojamiento,
  highlights = excluded.highlights,
  imagen_portada = excluded.imagen_portada,
  galeria = excluded.galeria,
  documentacion = excluded.documentacion,
  bases_y_condiciones = excluded.bases_y_condiciones,
  faq = excluded.faq,
  tags = excluded.tags,
  es_ejemplo = excluded.es_ejemplo,
  cliente_nombre = excluded.cliente_nombre,
  valida_hasta = excluded.valida_hasta,
  notas_internas = excluded.notas_internas,
  actualizado_por_nombre = excluded.actualizado_por_nombre,
  actualizado_en = now();

-- -------------------------------------------------------------------
-- CONFIGURACIÓN DEL SITIO
-- Solo se carga si todavía está vacía, para no pisar lo que el equipo
-- haya cargado desde el panel.
-- -------------------------------------------------------------------
update public.site_config
   set datos = '{"whatsapp":"","email":"","telefono":"","direccion":"","ciudad":"Asunción, Paraguay","mapsUrl":"","instagram":"palmatravelsrl","facebook":"","registroSenatur":"","heroTitulo":"Cada viaje, a tu medida","heroSubtitulo":"Paquetes armados con tiempo y viajes hechos a tu gusto, siempre con salida desde Asunción y alguien del equipo atrás tuyo de principio a fin.","heroImagen":"/muestra/hero-home.svg","mostrarPrecioEnGuaranies":false,"tipoCambioUsdGs":7300,"pesosMatch":{"tipoViaje":30,"presupuesto":25,"duracion":12,"mes":10,"companiaViaje":8,"ritmo":7,"region":5,"vuelo":3}}'::jsonb
 where id = 1
   and (datos is null or datos = '{}'::jsonb);


-- -------------------------------------------------------------------
-- LISTO
-- -------------------------------------------------------------------
select
  (select count(*) from public.paquetes)   as paquetes_cargados,
  (select count(*) from public.propuestas) as propuestas_cargadas;

